name: "Publish Home Assistant Add-on: MEGAcmd"

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/publish
        with:
          addon-path: megacmd
