name: "Publish Home Assistant Add-on: MEGAcmd"

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Publish
        uses: ./.github/actions/publish
        with:
          addon-path: megacmd
